name: tugas_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/Village.jpg 
    - images/android.png
    - images/sapi.jpg
    - images/cake.jpg
    - images/pizza.jpg
    - images/VoChrono.png
    
  fonts:
    - family: Oswald  # Nama font yang akan digunakan di kode
      fonts:
        - asset: fonts/Oswald/Oswald-Regular.ttf